apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow
  namespace: flux-system
spec:
  interval: 1m
  url: https://airflow.apache.org
---  
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: airflow
  namespace: flux-system  
spec:
  releaseName: airflow
  targetNamespace: airflow
  interval: 50m
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: airflow
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true 
    # ingress:
    #   enabled: true
    #   className: nginx       