---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 24h
  url: https://airflow.apache.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 12h
  values:
    installCRDs: true


apiVersion: helm.fluxcd.io/v1
spec:
  releaseName: airflow
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: airflow
    version: 8.0.9
  valuesFrom:
  - configMapKeyRef:
      name: airflow-values    
