apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 24h
  url: https://airflow.apache.org
---  
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: airflow
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    installCRDs: true    
    ingress:
      enabled: true
      className: nginx
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: airflow
#       version: "8.7.1"
#       sourceRef:
#         kind: HelmRepository
#         name: airflow
#         namespace: airflow
#       interval: 12h
#   values:
#     installCRDs: true
# ---  