---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: airflow
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: airflow
    version: 8.0.9
  valuesFrom:
  - configMapKeyRef:
      name: airflow-values    
