apiVersion: v1
kind: Namespace
metadata:
  name: apache
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---    
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apache
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: flux-system
spec:
  releaseName: apache
  targetNamespace: apache
  interval: 50m
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: apache
  install:
    remediation:
      retries: 3        
  values:
    ingress:
      enabled: true
      className: nginx
      hosts: k8s.aws.eqe.io
        http:
          paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: apache
                port: 
                  number: 80      

    tls:
    - hosts:
        - k8s.aws.eqe.io
      secretName: wildcard-tls-cert
