apiVersion: v1
kind: Namespace
metadata:
  name: apache
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: apache
  namespace: defaapachult
  # annotations:
  #   fluxcd.io/automated: "false"
  #   fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: apache
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: apache
    # version: 9.6.3
