apiVersion: v1
kind: Namespace
metadata:
  name: apache
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: apache
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/apache
  ref:
    tag: latest
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  targetNamespace: apache
  # releaseName: apache
  #     sourceRef:
  #       kind: HelmRepository
  #       name: podinfo  
  chart:
    repository: oci://registry-1.docker.io/bitnamicharts/apache
    name: apache
    # version: 9.6.3