apiVersion: v1
kind: Namespace
metadata:
  name: apache
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---    
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apache
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/apache
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: apache
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo