apiVersion: v1
kind: Namespace
metadata:
  name: apache
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: latest
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  releaseName: apache
  chart:
    repository: oci://registry-1.docker.io/bitnamicharts/apache
    name: apache
    # version: 9.6.3