apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
  name: podinfo
  namespace: podinfo
spec:
  rules:
  - host: podinfo.aws.eqe.io
    http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
        path: /
  tls:
  - hosts:
    - podinfo.aws.eqe.io
    secretName:  wildcard-tls-cert
