apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
  name: podinfo
  namespace: ingress-nginx
spec:
  rules:
  - host: podinfo.aws.eqe.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: podinfo
            port: 
              number: 9898
        
  tls:
  - hosts:
    - podinfo.aws.eqe.io
    secretName:  wildcard-tls-cert
