apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.helm.sh/stable
---  
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: sealed-secrets
  namespace: flux-system  
spec:
  releaseName: sealed-secrets
  targetNamespace: airflow
  interval: 50m
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: airflow
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true 
    ingress:
      enabled: true
      className: nginx       