apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---    
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 1m
  url: https://bitnami-labs.github.io/sealed-secrets
---  
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  targetNamespace:  kube-system
  interval: 50m
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    fullnameOverride: sealed-secrets-controller        