apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    replicaCount: 4
    ingress:
      enabled: true
      className: ingress-nginx
      annotations: 
        kubernetes.io/ingress.class: ingress-nginx 
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: k8s.aws.eqe.io
          paths:
            - path: /
              pathType: Exact
      tls:
         - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local              
      # className: ingress-nginx  
      # hosts:
      #   - host: k8s.aws.eqe.io
      #     paths:
      #       - path: /
      #         pathType: Exact
      #       - backend:
      #         serviceName: podinfo
      #         servicePort: 9898     
