apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      enabled: true
      className: nginx  
    # ingress:
    #   hosts:
    #     - host: k8s.aws.eqe.io
    #       paths:
    #         - path: /
    #           pathType: Exact
      # tls:
      #   - hosts:
      #     - k8s.aws.eqe.io
      #     secretName:  wildcard-tls-cert
              
